config/routes.rb
Rails.application.routes.draw do
  # get 'feature/show'

  # post 'feature/update'

  # get 'feature/index'

  # post 'feature/create'
  resources :feature, only: [:index, :show, :update, :create]

  resources :comment, only: [:index, :create]

  resources :invoice_datum, only: [:show, :update, :create]

  resources :command, only: [:index, :show, :update, :create]

  resources :phone, only: [:update]

  resources :estimate, only: [:index, :create, :update]

  resources :contract, only: [:index, :show, :create, :update]

  resources :invoice, only: [:index, :create, :update]

  resources :admin, only: [:index]
  get 'admin-command' => 'admin#command'
  post 'admin-command' => 'command#create'
  post 'admin-create-user' => 'admin#create_user'
  resources :user_interface, only: [:index]

  devise_for :users

  scope '(:locale)', locale: /en/ do

    resources :home, only: [:create, :index]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'home#index'
  end

end

app/models/command.rb
class Command < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :feature
  belongs_to :user
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :command
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  belongs_to :command
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :command
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :command
end

app/models/invoice_datum.rb
class InvoiceDatum < ApplicationRecord
  belongs_to :user
end

app/models/phone.rb
class Phone < ApplicationRecord
  validates :number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_interface.rb
class UserInterface < ApplicationRecord
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/command_helper.rb
module CommandHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contract_helper.rb
module ContractHelper
end

app/helpers/etimate_helper.rb
module EtimateHelper
end

app/helpers/feature_helper.rb
module FeatureHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/phone_helper.rb
module PhoneHelper
end

app/views/admin/_clients.html.erb
<div class="container">
  <% @users.each do |user| %>
    <div class="container">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="card w-100">
          <div class="card-body">
            <p class="card-text">
              <h4><%= user.email %></h4>
                  Acceder aux détails de ce client.    <%= link_to "voir les commandes", admin_command_path(id: user.id), class: "btn btn-primary", method: :get %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/_new_user.html.erb
<% if current_user.admin == true %>
  <div class="form">
    <h1>Créer un nouveau compte utilisateur</h1>
    <%= minimal_form_for @new_user, url:admin_create_user_path(id: 0), method: :post do |f| %>
      <%= f.input :email, placeholder: 'email utilisateur' %>
      <%= f.input :password, placeholder: 'définir un password de base' %>
      <%= f.button :submit, 'créer' %>
    <% end %>
  </div>
<% end %>

app/views/admin/_phones.html.erb
<div class="container">
  <% if @phones %>
    <% @phones.each do |phone| %>
      <% if phone.called == false %>
        <div class="container">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="card w-100">
              <div class="card-body">
                <p class="card-text">
                  <h4><%= phone.number %></h4>
                  Avez vous appelé ce client?
                  <%= link_to t('.set_as_called'), phone_path(phone.id), class: "btn btn-primary", method: :put  %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/admin/command.html.erb
<div class="container">
  <h2><%= @user.email%>'s commands</h2>
  <% if @invoice_data %>
    <%= "#{@invoice_data.compagny_name}" %><br/>
    <%= "#{@invoice_data.adress}" %><br/>
    <%= "#{@invoice_data.number}/#{@invoice_data.siren}" %><br/><br/><br/>
    <%= render 'admin/command/update_invoice_data' %>
  <% else %>
    <%= render 'admin/command/invoice_data_form', object: @new_invoice_data %>
  <% end %>

  <%= render 'admin/command/command_card', object: @commands, object: @user %>
  <%= render 'admin/command/new_command_form', object: @new_command, object: @user %>
</div>

app/views/admin/index.html.erb
<h1>My admin panel</h1>

<%= render 'phones', object: @phones %>

<%= render 'clients', object: @users %>

<%= render 'new_user', object: @new_user %>

app/views/admin/show.html.erb
<h1>My admin panel</h1>

<%= render 'phones', object: @phones %>

<%= render 'clients', object: @users %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible no-margin-and-b-r" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="agency-footer", id="custom-agency-footer">
  <a href="#" class="go-top"><i class="fa fa-angle-up"></i>TOP</a>
  <div class="row">
    <div class="col-12">
      <div class="cta text-center padding-bottom-70-px container-top-margin">
        <div id="custom-agency-footer">
          <h1 class="cta-title">Lancez votre business dans une autre dimension dès aujourd'hui.</h1>
          <a class="btn-shadow btn-shadow-info mr-md-1" href="#">On en parle?</a>
          <a class="btn-outline ml-md-1" href="#">Nos services</a>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" >
      <div class="col-md-3">
        <h4>Liens</h4>
        <a href="#" class="legal">Mentions légales</a>
        <a href="#" class="legal">Nous dire bonjour</a>
        <a href="#" class="legal">Espace client</a>
      </div>
      <div class="col-md-3">
        <h4>Adresse</h4>
        <p>10 fausse avenue<br>75001 Paris<br>France</p>
      </div>
      <div class="col-md-3">
        <h4>Contact</h4>
        <p>contact@valto.fr<br>9h - 17h UTC+2</p>
      </div>
      <div class="col-md-3">
        <h4>Social</h4>
        <a href="#" class="social first"><i class="fa fa-facebook"></i></a>
        <a href="#" class="social"><i class="fa fa-twitter"></i></a>
        <a href="#" class="social"><i class="fa fa-dribbble"></i></a>
        <a href="#" class="social"><i class="fa fa-github"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="valtonavbar navbar navbar-dark navbar-expand-lg" role="navigation">
  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'Valto', home_index_path, class: 'navbar-brand', method: :get %>

  <div class="collapse navbar-collapse justify-content-end" id="navbar-collapse navbar-padding-bottom">
    <ul class="navbar-nav">
      <li class="nav-item">
          
          TEST
          
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        <% end %>
      </li>
      <li class="nav-item my-auto">
        <% if user_signed_in? %>
          <% if current_user.admin %>
            <%= link_to "admin interface", admin_index_path, class: "nav-link nav-link--rounded" %>
          <% else %>
            <%= link_to "my interface", command_index_path, class: "nav-link nav-link--rounded" %>
          <% end %>
        <% else %>
          <%= link_to "Connexion", new_user_session_path, class: "nav-link nav-link--rounded" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>